export const REFERRAL_STATUSES = Object.freeze({
  PENDING: "Pending",
  ACCEPTED: "Not Connected", // Legacy
  ACKNOWLEDGED: "Acknowledged / Accepted",
  CALLED_NOT_ANSWERED: "Called but Not Answered",
  DISCUSSION_IN_PROGRESS: "Discussion in Progress",
  PROPOSAL_SENT: "Proposal Sent / Quote Sent",
  DEAL_LOST: "Deal Lost",
  DEAL_WON: "Deal Won",
  CANCELLED: "Cancelled",
  WORK_IN_PROGRESS: "Work in Progress",
  WORK_COMPLETED: "Work Completed",
  INVOICE_SENT: "Invoice Sent / Payment Pending",
  RECEIVED_FULL_AND_FINAL_PAYMENT: "Received Full and Final Payment",
  RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB:
    "Received Part Payment and Transferred to UJustBe",
  AGREED_PERCENT_TRANSFERRED_TO_UJB: "Agreed % Transferred to UJustBe",
  CLOSED: "Closed",
  HOLD: "Hold",
  REJECTED: "Rejected",
});

export const REFERRAL_STATUS_OPTIONS = Object.freeze([
  REFERRAL_STATUSES.PENDING,
  REFERRAL_STATUSES.ACCEPTED,
  REFERRAL_STATUSES.ACKNOWLEDGED,
  REFERRAL_STATUSES.CALLED_NOT_ANSWERED,
  REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
  REFERRAL_STATUSES.PROPOSAL_SENT,
  REFERRAL_STATUSES.DEAL_LOST,
  REFERRAL_STATUSES.DEAL_WON,
  REFERRAL_STATUSES.CANCELLED,
  REFERRAL_STATUSES.WORK_IN_PROGRESS,
  REFERRAL_STATUSES.WORK_COMPLETED,
  REFERRAL_STATUSES.INVOICE_SENT,
  REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT,
  REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
  REFERRAL_STATUSES.AGREED_PERCENT_TRANSFERRED_TO_UJB,
  REFERRAL_STATUSES.CLOSED,
  REFERRAL_STATUSES.HOLD,
  REFERRAL_STATUSES.REJECTED,
]);

const STATUS_ALIASES = new Map([
  ["received full & final payment", REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT],
  [
    "received full and final payment",
    REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT,
  ],
  [
    "received part payment & transferred to ujustbe",
    REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
  ],
  [
    "received part payment and transferred to ujustbe",
    REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
  ],
  ["reject", REFERRAL_STATUSES.REJECTED],
]);

export function normalizeReferralStatus(value) {
  const raw = String(value || "").trim();

  if (!raw) {
    return REFERRAL_STATUSES.PENDING;
  }

  const directMatch = REFERRAL_STATUS_OPTIONS.find((status) => status === raw);

  if (directMatch) {
    return directMatch;
  }

  const alias = STATUS_ALIASES.get(raw.toLowerCase());
  return alias || raw;
}

export const REFERRAL_STATUS_TRANSITIONS = Object.freeze({
  [REFERRAL_STATUSES.PENDING]: new Set([
    REFERRAL_STATUSES.ACKNOWLEDGED,
    REFERRAL_STATUSES.ACCEPTED,
    REFERRAL_STATUSES.CALLED_NOT_ANSWERED,
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.REJECTED,
  ]),
  [REFERRAL_STATUSES.ACKNOWLEDGED]: new Set([
    REFERRAL_STATUSES.CALLED_NOT_ANSWERED,
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.REJECTED,
  ]),
  [REFERRAL_STATUSES.ACCEPTED]: new Set([
    REFERRAL_STATUSES.CALLED_NOT_ANSWERED,
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.REJECTED,
  ]),
  [REFERRAL_STATUSES.CALLED_NOT_ANSWERED]: new Set([
    REFERRAL_STATUSES.ACKNOWLEDGED,
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.REJECTED,
  ]),
  [REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS]: new Set([
    REFERRAL_STATUSES.PROPOSAL_SENT,
    REFERRAL_STATUSES.DEAL_LOST,
    REFERRAL_STATUSES.DEAL_WON,
    REFERRAL_STATUSES.HOLD,
  ]),
  [REFERRAL_STATUSES.PROPOSAL_SENT]: new Set([
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.DEAL_LOST,
    REFERRAL_STATUSES.DEAL_WON,
    REFERRAL_STATUSES.HOLD,
  ]),
  [REFERRAL_STATUSES.DEAL_WON]: new Set([
    REFERRAL_STATUSES.WORK_IN_PROGRESS,
    REFERRAL_STATUSES.WORK_COMPLETED,
    REFERRAL_STATUSES.CANCELLED,
    REFERRAL_STATUSES.HOLD,
  ]),
  [REFERRAL_STATUSES.WORK_IN_PROGRESS]: new Set([
    REFERRAL_STATUSES.WORK_COMPLETED,
    REFERRAL_STATUSES.CANCELLED,
    REFERRAL_STATUSES.HOLD,
  ]),
  [REFERRAL_STATUSES.WORK_COMPLETED]: new Set([
    REFERRAL_STATUSES.INVOICE_SENT,
    REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
    REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT,
  ]),
  [REFERRAL_STATUSES.INVOICE_SENT]: new Set([
    REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
    REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT,
  ]),
  [REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB]: new Set([
    REFERRAL_STATUSES.INVOICE_SENT,
    REFERRAL_STATUSES.RECEIVED_PART_PAYMENT_AND_TRANSFERRED_TO_UJB,
    REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT,
    REFERRAL_STATUSES.AGREED_PERCENT_TRANSFERRED_TO_UJB,
  ]),
  [REFERRAL_STATUSES.RECEIVED_FULL_AND_FINAL_PAYMENT]: new Set([
    REFERRAL_STATUSES.AGREED_PERCENT_TRANSFERRED_TO_UJB,
  ]),
  [REFERRAL_STATUSES.AGREED_PERCENT_TRANSFERRED_TO_UJB]: new Set([
    REFERRAL_STATUSES.CLOSED,
  ]),
  [REFERRAL_STATUSES.HOLD]: new Set([
    REFERRAL_STATUSES.DISCUSSION_IN_PROGRESS,
    REFERRAL_STATUSES.WORK_IN_PROGRESS,
    REFERRAL_STATUSES.DEAL_LOST,
    REFERRAL_STATUSES.CANCELLED,
  ]),
  [REFERRAL_STATUSES.CANCELLED]: new Set([]),
  [REFERRAL_STATUSES.DEAL_LOST]: new Set([]),
  [REFERRAL_STATUSES.REJECTED]: new Set([]),
  [REFERRAL_STATUSES.CLOSED]: new Set([]),
});

export function canTransitionReferralStatus(currentStatus, nextStatus) {
  const current = normalizeReferralStatus(currentStatus);
  const next = normalizeReferralStatus(nextStatus);

  if (current === next) {
    return true;
  }

  const allowed = REFERRAL_STATUS_TRANSITIONS[current];
  return Boolean(allowed && allowed.has(next));
}

export function getAvailableNextStatuses(currentStatus) {
  const current = normalizeReferralStatus(currentStatus);
  const allowed = REFERRAL_STATUS_TRANSITIONS[current] || new Set();
  
  // Always include the current status as an option
  return [current, ...Array.from(allowed)];
}

export function isFinalReferralStatus(status) {
  const normalized = normalizeReferralStatus(status);

  return (
    normalized === REFERRAL_STATUSES.REJECTED ||
    normalized === REFERRAL_STATUSES.DEAL_LOST ||
    normalized === REFERRAL_STATUSES.CANCELLED ||
    normalized === REFERRAL_STATUSES.CLOSED ||
    normalized === REFERRAL_STATUSES.AGREED_PERCENT_TRANSFERRED_TO_UJB
  );
}

